DROP TABLE IF EXISTS AnnualCountryStats;
DROP TABLE IF EXISTS AnnualDemographicStats;
DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS WorksIn;
DROP TABLE IF EXISTS Year;
DROP TABLE IF EXISTS Demographic;